### PR TITLE
FE-609 | fix: do not output Exists result as object

### LINKED ISSUE #33: Exists return empty object when ref not exist.
`Exists(Match(Index("unique_user_by_email"), "notexist@example.com"))`

From this query,

Fauna shell return false.
But vscode extension return empty object.
[faunadb-js](https://github.com/fauna/faunadb-js) also return boolean.
So I think this vscode issue.

image

### PR DESCRIPTION
**Pull request by fauna-ryanharris**
### Notes
[Jira ticket](https://faunadb.atlassian.net/browse/FE-609)

Previously, when running the `Exists` function, users were getting an empty `{}` instead of a `true` or `false` return value. It seems we were assuming our return value would be an object and formatting it based on that. Now, if the return from `runFQLQuery` is not an object, we'll just stringify and output it.

**NOTE:** This also fixes an issue with string outputs like the example below, which is what currently happens on `master`:
```
LowerCase("HI THERE")
{ 0: "h", 1: "i", 2: " ", 3: "t", 4: "h", 5: "e", 6: "r", 7: "e" }
```

Closed #33 

### Screencap
https://www.loom.com/share/e0d1032fb0d84483b1d583bc5a8fc325

### CODE REVIEW

**Comment by fauna-ryanharris** [comment]
@BrunoQuaresma I checked the functionality on `master` and it seems we're not currently supporting multiple queries in the same call. Is that expected?

For example, I tried:
```
Paginate(Collections())
Paginate(Databases())
```
...and only received the results for the second query.

File: src/runQueryCommand.ts [hunk 1]
```diff
@@ -43,18 +43,29 @@ export default (
...
-        .trim()
-        .replace(/^(\({)/, '{')
-        .replace(/(}\);$)/g, '}')
-        .replace(';', '')
-    );
+    typeof result === "object"
+      ? outputChannel.appendLine(
+          prettier
+            // @ts-ignore comment
+            .format(`(${Expr.toString(q.Object(result))})`, {
```
Comment (fauna-ryanharris) [inline src/runQueryCommand.ts:50]: This q.Object seems to be what was causing the issue when trying to output a boolean value.

File: src/specialTypes.ts [hunk 2]
```diff
@@ -0,0 +1,73 @@
+// @ts-nocheck
```
Comment (fauna-ryanharris) [inline src/specialTypes.ts:1]: This file is copied directly from Dashboard 👍

File: src/fql.ts [hunk 3]
```diff
@@ -221,3 +224,54 @@ export function runFQLQuery(code: string, client: Client) {
     return Promise.reject(error);
   }
 }
+
+export function stringify(obj: object) {
```
Comment (fauna-ryanharris) [inline src/fql.ts:228]: These functions are pulled directly from the Dashboard codebase 👍

**Comment by BrunoQuaresma** [comment]
Worked well?

**Comment by fauna-ryanharris** [comment]
> Worked well?

@BrunoQuaresma Yup! I did some testing with queries that return objects, strings and booleans. All of them output results as expected.
